uglifyjs js/sound.js \
    js/json.js \
    js/title.js \
    js/controls.js \
    js/topbar.js \
    js/flashmessage.js \
    js/flash.js \
    js/player.js \
    js/players.js \
    js/scoreboard.js \
    js/card.js \
    js/discardcard.js \
    js/interactivecard.js \
    js/drawcard.js \
    js/playercard.js \
    js/colorselectorbutton.js \
    js/colorselector.js \
    js/wildcard.js \
    js/tray.js \
    js/hand.js \
    js/game.js \
    > ../static/runo.min.js
